
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: unsaved
* name: Font
* family: MS Shell Dlg 2
* size: 14
* style: Обычный
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Edge 102
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/
#pragma once
#include <stdint.h>

 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x20[17] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x20 = { image_data_Font_0x20,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x21[17] = {
    // ████
    // ████
    // ████
    // ████
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // ████
    // █∙██
    // █∙██
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xf0, 
    0xb0, 
    0xb0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x21 = { image_data_Font_0x21,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x22[17] = {
    // ██████
    // ██████
    // ██████
    // █∙██∙█
    // █∙██∙█
    // █∙██∙█
    // █∙██∙█
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xb4, 
    0xb4, 
    0xb4, 
    0xb4, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x22 = { image_data_Font_0x22,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x23[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ████∙██∙██
    // ████∙██∙██
    // ███∙██∙███
    // ██∙∙∙∙∙∙∙█
    // ███∙██∙███
    // ███∙██∙███
    // █∙∙∙∙∙∙∙██
    // ██∙██∙████
    // ██∙██∙████
    // ██∙██∙████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf6, 0xc0, 
    0xf6, 0xc0, 
    0xed, 0xc0, 
    0xc0, 0x40, 
    0xed, 0xc0, 
    0xed, 0xc0, 
    0x80, 0xc0, 
    0xdb, 0xc0, 
    0xdb, 0xc0, 
    0xdb, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x23 = { image_data_Font_0x23,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x24[17] = {
    // ████████
    // ████████
    // ████████
    // ████∙███
    // ████∙███
    // ██∙∙∙∙██
    // █∙██∙█∙█
    // █∙██∙███
    // █∙██∙███
    // ██∙∙∙∙██
    // ████∙█∙█
    // ████∙█∙█
    // █∙██∙█∙█
    // ██∙∙∙∙██
    // ████∙███
    // ████∙███
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xf7, 
    0xf7, 
    0xc3, 
    0xb5, 
    0xb7, 
    0xb7, 
    0xc3, 
    0xf5, 
    0xf5, 
    0xb5, 
    0xc3, 
    0xf7, 
    0xf7, 
    0xff
};
static const tImage Font_0x24 = { image_data_Font_0x24,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x25[34] = {
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ██∙∙∙████∙████
    // █∙███∙██∙█████
    // █∙███∙██∙█████
    // █∙███∙█∙██████
    // █∙███∙█∙█∙∙∙██
    // ██∙∙∙█∙█∙███∙█
    // ██████∙█∙███∙█
    // █████∙██∙███∙█
    // █████∙██∙███∙█
    // ████∙████∙∙∙██
    // ██████████████
    // ██████████████
    // ██████████████
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xc7, 0xbc, 
    0xbb, 0x7c, 
    0xbb, 0x7c, 
    0xba, 0xfc, 
    0xba, 0x8c, 
    0xc5, 0x74, 
    0xfd, 0x74, 
    0xfb, 0x74, 
    0xfb, 0x74, 
    0xf7, 0x8c, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc
};
static const tImage Font_0x25 = { image_data_Font_0x25,
    14, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x26[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // █∙∙∙∙████
    // ∙████∙███
    // ∙████∙███
    // ∙███∙████
    // █∙∙∙██∙██
    // ∙██∙██∙██
    // ∙███∙█∙██
    // ∙████∙███
    // ∙████∙∙██
    // █∙∙∙∙██∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x87, 0x80, 
    0x7b, 0x80, 
    0x7b, 0x80, 
    0x77, 0x80, 
    0x8d, 0x80, 
    0x6d, 0x80, 
    0x75, 0x80, 
    0x7b, 0x80, 
    0x79, 0x80, 
    0x86, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x26 = { image_data_Font_0x26,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x27[17] = {
    // ███
    // ███
    // ███
    // █∙█
    // █∙█
    // █∙█
    // █∙█
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    // ███
    0xe0, 
    0xe0, 
    0xe0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0, 
    0xe0
};
static const tImage Font_0x27 = { image_data_Font_0x27,
    3, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x28[17] = {
    // █████
    // █████
    // █████
    // ████∙
    // ███∙█
    // ██∙██
    // ██∙██
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // ██∙██
    // ██∙██
    // ███∙█
    // ████∙
    0xf8, 
    0xf8, 
    0xf8, 
    0xf0, 
    0xe8, 
    0xd8, 
    0xd8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xd8, 
    0xd8, 
    0xe8, 
    0xf0
};
static const tImage Font_0x28 = { image_data_Font_0x28,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x29[17] = {
    // █████
    // █████
    // █████
    // ∙████
    // █∙███
    // ██∙██
    // ██∙██
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ██∙██
    // ██∙██
    // █∙███
    // ∙████
    0xf8, 
    0xf8, 
    0xf8, 
    0x78, 
    0xb8, 
    0xd8, 
    0xd8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xd8, 
    0xd8, 
    0xb8, 
    0x78
};
static const tImage Font_0x29 = { image_data_Font_0x29,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2a[17] = {
    // ████████
    // ████████
    // ████████
    // ███∙████
    // ∙██∙██∙█
    // █∙█∙█∙██
    // ██∙∙∙███
    // █∙█∙█∙██
    // ∙██∙██∙█
    // ███∙████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xef, 
    0x6d, 
    0xab, 
    0xc7, 
    0xab, 
    0x6d, 
    0xef, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x2a = { image_data_Font_0x2a,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2b[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ████∙█████
    // ████∙█████
    // ████∙█████
    // █∙∙∙∙∙∙∙██
    // ████∙█████
    // ████∙█████
    // ████∙█████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf7, 0xc0, 
    0xf7, 0xc0, 
    0xf7, 0xc0, 
    0x80, 0xc0, 
    0xf7, 0xc0, 
    0xf7, 0xc0, 
    0xf7, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x2b = { image_data_Font_0x2b,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2c[17] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ██∙█
    // ██∙█
    // ██∙█
    // █∙██
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xb0, 
    0xf0
};
static const tImage Font_0x2c = { image_data_Font_0x2c,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2d[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // ∙∙∙∙█
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0x08, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x2d = { image_data_Font_0x2d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2e[17] = {
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // ████
    // █∙██
    // █∙██
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xb0, 
    0xb0, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x2e = { image_data_Font_0x2e,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x2f[17] = {
    // █████
    // █████
    // █████
    // ████∙
    // ████∙
    // ███∙█
    // ███∙█
    // ███∙█
    // ██∙██
    // ██∙██
    // ██∙██
    // █∙███
    // █∙███
    // █∙███
    // ∙████
    // ∙████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf0, 
    0xf0, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0x78, 
    0x78, 
    0xf8
};
static const tImage Font_0x2f = { image_data_Font_0x2f,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x30[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙███
    // █∙███∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙██
    // ██∙∙∙███
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc7, 
    0xbb, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xbb, 
    0xc7, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x30 = { image_data_Font_0x30,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x31[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████∙███
    // ██∙∙∙███
    // ████∙███
    // ████∙███
    // ████∙███
    // ████∙███
    // ████∙███
    // ████∙███
    // ████∙███
    // ██∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xf7, 
    0xc7, 
    0xf7, 
    0xf7, 
    0xf7, 
    0xf7, 
    0xf7, 
    0xf7, 
    0xf7, 
    0xc1, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x31 = { image_data_Font_0x31,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x32[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙██
    // █∙████∙█
    // ██████∙█
    // ██████∙█
    // █████∙██
    // ████∙███
    // ███∙████
    // ██∙█████
    // █∙██████
    // █∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc3, 
    0xbd, 
    0xfd, 
    0xfd, 
    0xfb, 
    0xf7, 
    0xef, 
    0xdf, 
    0xbf, 
    0x81, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x32 = { image_data_Font_0x32,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x33[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙██
    // █∙████∙█
    // ██████∙█
    // ██████∙█
    // ███∙∙∙██
    // ██████∙█
    // ██████∙█
    // ██████∙█
    // █∙████∙█
    // ██∙∙∙∙██
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc3, 
    0xbd, 
    0xfd, 
    0xfd, 
    0xe3, 
    0xfd, 
    0xfd, 
    0xfd, 
    0xbd, 
    0xc3, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x33 = { image_data_Font_0x33,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x34[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // █████∙██
    // ████∙∙██
    // ███∙█∙██
    // ██∙██∙██
    // █∙███∙██
    // ∙████∙██
    // ∙∙∙∙∙∙∙█
    // █████∙██
    // █████∙██
    // █████∙██
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xfb, 
    0xf3, 
    0xeb, 
    0xdb, 
    0xbb, 
    0x7b, 
    0x01, 
    0xfb, 
    0xfb, 
    0xfb, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x34 = { image_data_Font_0x34,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x35[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // █∙██████
    // █∙██████
    // █∙██████
    // █∙∙∙∙∙██
    // ██████∙█
    // ██████∙█
    // ██████∙█
    // █∙████∙█
    // ██∙∙∙∙██
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xbf, 
    0xbf, 
    0xbf, 
    0x83, 
    0xfd, 
    0xfd, 
    0xfd, 
    0xbd, 
    0xc3, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x35 = { image_data_Font_0x35,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x36[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ███∙∙∙██
    // █∙∙█████
    // █∙██████
    // ∙███████
    // ∙∙∙∙∙███
    // ∙████∙██
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙██
    // ██∙∙∙███
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xe3, 
    0x9f, 
    0xbf, 
    0x7f, 
    0x07, 
    0x7b, 
    0x7d, 
    0x7d, 
    0xbb, 
    0xc7, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x36 = { image_data_Font_0x36,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x37[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙∙█
    // ██████∙█
    // █████∙██
    // █████∙██
    // █████∙██
    // ████∙███
    // ████∙███
    // ███∙████
    // ███∙████
    // ██∙█████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x81, 
    0xfd, 
    0xfb, 
    0xfb, 
    0xfb, 
    0xf7, 
    0xf7, 
    0xef, 
    0xef, 
    0xdf, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x37 = { image_data_Font_0x37,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x38[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙∙∙∙∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙∙∙∙∙██
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x83, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x83, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x83, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x38 = { image_data_Font_0x38,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x39[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙███
    // █∙███∙██
    // ∙█████∙█
    // ∙█████∙█
    // █∙████∙█
    // ██∙∙∙∙∙█
    // ██████∙█
    // █████∙██
    // ████∙∙██
    // █∙∙∙████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc7, 
    0xbb, 
    0x7d, 
    0x7d, 
    0xbd, 
    0xc1, 
    0xfd, 
    0xfb, 
    0xf3, 
    0x8f, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x39 = { image_data_Font_0x39,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3a[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // ██∙██
    // ██∙██
    // █████
    // █████
    // █████
    // █████
    // ██∙██
    // ██∙██
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xd8, 
    0xd8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xd8, 
    0xd8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x3a = { image_data_Font_0x3a,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3b[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // ██∙██
    // ██∙██
    // █████
    // █████
    // █████
    // █████
    // ██∙██
    // ██∙██
    // ██∙██
    // █∙███
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xd8, 
    0xd8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xb8, 
    0xf8
};
static const tImage Font_0x3b = { image_data_Font_0x3b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3c[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███████∙██
    // █████∙∙███
    // ███∙∙█████
    // █∙∙███████
    // ███∙∙█████
    // █████∙∙███
    // ███████∙██
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xfe, 0xc0, 
    0xf9, 0xc0, 
    0xe7, 0xc0, 
    0x9f, 0xc0, 
    0xe7, 0xc0, 
    0xf9, 0xc0, 
    0xfe, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x3c = { image_data_Font_0x3c,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3d[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // █∙∙∙∙∙∙∙∙█
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x80, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x80, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x3d = { image_data_Font_0x3d,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3e[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // █∙████████
    // ██∙∙██████
    // ████∙∙████
    // ██████∙∙██
    // ████∙∙████
    // ██∙∙██████
    // █∙████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xbf, 0xc0, 
    0xcf, 0xc0, 
    0xf3, 0xc0, 
    0xfc, 0xc0, 
    0xf3, 0xc0, 
    0xcf, 0xc0, 
    0xbf, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x3e = { image_data_Font_0x3e,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x3f[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // █∙∙∙∙██
    // ∙████∙█
    // █████∙█
    // █████∙█
    // ███∙∙██
    // ██∙████
    // ██∙████
    // ███████
    // ██∙████
    // ██∙████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x86, 
    0x7a, 
    0xfa, 
    0xfa, 
    0xe6, 
    0xde, 
    0xde, 
    0xfe, 
    0xde, 
    0xde, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x3f = { image_data_Font_0x3f,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x40[34] = {
    // █████████████
    // █████████████
    // █████████████
    // █████████████
    // ████∙∙∙∙∙████
    // ██∙∙█████∙███
    // █∙████████∙██
    // █∙███∙∙∙∙██∙█
    // ∙███∙███∙██∙█
    // ∙██∙████∙██∙█
    // ∙██∙████∙██∙█
    // ∙██∙████∙██∙█
    // █∙██∙∙∙∙∙∙∙██
    // █∙███████████
    // ██∙∙█████████
    // ████∙∙∙∙∙████
    // █████████████
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xff, 0xf8, 
    0xf0, 0x78, 
    0xcf, 0xb8, 
    0xbf, 0xd8, 
    0xb8, 0x68, 
    0x77, 0x68, 
    0x6f, 0x68, 
    0x6f, 0x68, 
    0x6f, 0x68, 
    0xb0, 0x18, 
    0xbf, 0xf8, 
    0xcf, 0xf8, 
    0xf0, 0x78, 
    0xff, 0xf8
};
static const tImage Font_0x40 = { image_data_Font_0x40,
    13, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x41[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ███∙████
    // ██∙█∙███
    // ██∙█∙███
    // ██∙█∙███
    // ██∙█∙███
    // █∙███∙██
    // █∙∙∙∙∙██
    // █∙███∙██
    // ∙█████∙█
    // ∙█████∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xef, 
    0xd7, 
    0xd7, 
    0xd7, 
    0xd7, 
    0xbb, 
    0x83, 
    0xbb, 
    0x7d, 
    0x7d, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x41 = { image_data_Font_0x41,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x42[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙███
    // ∙████∙██
    // ∙████∙██
    // ∙████∙██
    // ∙∙∙∙∙███
    // ∙████∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙████∙██
    // ∙∙∙∙∙███
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x07, 
    0x7b, 
    0x7b, 
    0x7b, 
    0x07, 
    0x7b, 
    0x7d, 
    0x7d, 
    0x7b, 
    0x07, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x42 = { image_data_Font_0x42,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x43[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ███∙∙∙∙██
    // █∙∙████∙█
    // █∙███████
    // ∙████████
    // ∙████████
    // ∙████████
    // ∙████████
    // █∙███████
    // █∙∙████∙█
    // ███∙∙∙∙██
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xe1, 0x80, 
    0x9e, 0x80, 
    0xbf, 0x80, 
    0x7f, 0x80, 
    0x7f, 0x80, 
    0x7f, 0x80, 
    0x7f, 0x80, 
    0xbf, 0x80, 
    0x9e, 0x80, 
    0xe1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x43 = { image_data_Font_0x43,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x44[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ∙∙∙∙∙∙████
    // ∙█████∙∙██
    // ∙██████∙██
    // ∙███████∙█
    // ∙███████∙█
    // ∙███████∙█
    // ∙███████∙█
    // ∙██████∙██
    // ∙█████∙∙██
    // ∙∙∙∙∙∙████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x03, 0xc0, 
    0x7c, 0xc0, 
    0x7e, 0xc0, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7e, 0xc0, 
    0x7c, 0xc0, 
    0x03, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x44 = { image_data_Font_0x44,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x45[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙█
    // ∙███████
    // ∙███████
    // ∙███████
    // ∙∙∙∙∙∙∙█
    // ∙███████
    // ∙███████
    // ∙███████
    // ∙███████
    // ∙∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x01, 
    0x7f, 
    0x7f, 
    0x7f, 
    0x01, 
    0x7f, 
    0x7f, 
    0x7f, 
    0x7f, 
    0x01, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x45 = { image_data_Font_0x45,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x46[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ∙∙∙∙∙∙█
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙∙∙∙∙∙█
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x02, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x02, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x46 = { image_data_Font_0x46,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x47[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ███∙∙∙∙██
    // █∙∙████∙█
    // █∙███████
    // ∙████████
    // ∙████████
    // ∙███∙∙∙∙█
    // ∙██████∙█
    // █∙█████∙█
    // █∙∙████∙█
    // ███∙∙∙∙██
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xe1, 0x80, 
    0x9e, 0x80, 
    0xbf, 0x80, 
    0x7f, 0x80, 
    0x7f, 0x80, 
    0x70, 0x80, 
    0x7e, 0x80, 
    0xbe, 0x80, 
    0x9e, 0x80, 
    0xe1, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x47 = { image_data_Font_0x47,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x48[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙∙∙∙∙∙∙∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x00, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x48 = { image_data_Font_0x48,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x49[17] = {
    // ████
    // ████
    // ████
    // ████
    // ∙∙∙█
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // █∙██
    // ∙∙∙█
    // ████
    // ████
    // ████
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0x10, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0xb0, 
    0x10, 
    0xf0, 
    0xf0, 
    0xf0
};
static const tImage Font_0x49 = { image_data_Font_0x49,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4a[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // █∙∙∙∙█
    // ████∙█
    // ████∙█
    // ████∙█
    // ████∙█
    // ████∙█
    // ████∙█
    // ████∙█
    // ████∙█
    // ∙∙∙∙██
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0x84, 
    0xf4, 
    0xf4, 
    0xf4, 
    0xf4, 
    0xf4, 
    0xf4, 
    0xf4, 
    0xf4, 
    0x0c, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x4a = { image_data_Font_0x4a,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4b[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // ∙████∙██
    // ∙███∙███
    // ∙██∙████
    // ∙█∙█████
    // ∙∙∙█████
    // ∙██∙████
    // ∙███∙███
    // ∙████∙██
    // ∙█████∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0x7b, 
    0x77, 
    0x6f, 
    0x5f, 
    0x1f, 
    0x6f, 
    0x77, 
    0x7b, 
    0x7d, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x4b = { image_data_Font_0x4b,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4c[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙∙∙∙∙∙█
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x02, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x4c = { image_data_Font_0x4c,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4d[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ∙∙█████∙∙█
    // ∙∙█████∙∙█
    // ∙█∙███∙█∙█
    // ∙█∙███∙█∙█
    // ∙██∙█∙██∙█
    // ∙██∙█∙██∙█
    // ∙███∙███∙█
    // ∙███∙███∙█
    // ∙███████∙█
    // ∙███████∙█
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x3e, 0x40, 
    0x3e, 0x40, 
    0x5d, 0x40, 
    0x5d, 0x40, 
    0x6b, 0x40, 
    0x6b, 0x40, 
    0x77, 0x40, 
    0x77, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x4d = { image_data_Font_0x4d,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4e[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ∙∙█████∙█
    // ∙∙█████∙█
    // ∙█∙████∙█
    // ∙█∙████∙█
    // ∙██∙███∙█
    // ∙███∙██∙█
    // ∙███∙██∙█
    // ∙████∙█∙█
    // ∙█████∙∙█
    // ∙█████∙∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x3e, 0x80, 
    0x3e, 0x80, 
    0x5e, 0x80, 
    0x5e, 0x80, 
    0x6e, 0x80, 
    0x76, 0x80, 
    0x76, 0x80, 
    0x7a, 0x80, 
    0x7c, 0x80, 
    0x7c, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x4e = { image_data_Font_0x4e,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x4f[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙████
    // █∙∙███∙∙██
    // █∙█████∙██
    // ∙███████∙█
    // ∙███████∙█
    // ∙███████∙█
    // ∙███████∙█
    // █∙█████∙██
    // █∙∙███∙∙██
    // ███∙∙∙████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe3, 0xc0, 
    0x9c, 0xc0, 
    0xbe, 0xc0, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0xbe, 0xc0, 
    0x9c, 0xc0, 
    0xe3, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x4f = { image_data_Font_0x4f,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x50[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙███
    // ∙████∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙████∙██
    // ∙∙∙∙∙███
    // ∙███████
    // ∙███████
    // ∙███████
    // ∙███████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x07, 
    0x7b, 
    0x7d, 
    0x7d, 
    0x7b, 
    0x07, 
    0x7f, 
    0x7f, 
    0x7f, 
    0x7f, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x50 = { image_data_Font_0x50,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x51[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ███∙∙∙████
    // █∙∙███∙∙██
    // █∙█████∙██
    // ∙███████∙█
    // ∙███████∙█
    // ∙███████∙█
    // ∙███████∙█
    // █∙█████∙██
    // █∙∙███∙∙██
    // ███∙∙∙████
    // █████∙████
    // █████∙████
    // ██████∙∙∙█
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xe3, 0xc0, 
    0x9c, 0xc0, 
    0xbe, 0xc0, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0x7f, 0x40, 
    0xbe, 0xc0, 
    0x9c, 0xc0, 
    0xe3, 0xc0, 
    0xfb, 0xc0, 
    0xfb, 0xc0, 
    0xfc, 0x40
};
static const tImage Font_0x51 = { image_data_Font_0x51,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x52[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ∙∙∙∙∙████
    // ∙████∙███
    // ∙████∙███
    // ∙████∙███
    // ∙████∙███
    // ∙∙∙∙∙████
    // ∙███∙████
    // ∙████∙███
    // ∙█████∙██
    // ∙██████∙█
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x07, 0x80, 
    0x7b, 0x80, 
    0x7b, 0x80, 
    0x7b, 0x80, 
    0x7b, 0x80, 
    0x07, 0x80, 
    0x77, 0x80, 
    0x7b, 0x80, 
    0x7d, 0x80, 
    0x7e, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x52 = { image_data_Font_0x52,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x53[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // █∙∙∙∙∙██
    // ∙█████∙█
    // ∙███████
    // ∙███████
    // █∙∙∙████
    // ████∙∙██
    // ██████∙█
    // ██████∙█
    // ∙█████∙█
    // █∙∙∙∙∙██
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x83, 
    0x7d, 
    0x7f, 
    0x7f, 
    0x8f, 
    0xf3, 
    0xfd, 
    0xfd, 
    0x7d, 
    0x83, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x53 = { image_data_Font_0x53,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x54[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x00, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x54 = { image_data_Font_0x54,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x55[34] = {
    // █████████
    // █████████
    // █████████
    // █████████
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // ∙██████∙█
    // █∙████∙██
    // ██∙∙∙∙███
    // █████████
    // █████████
    // █████████
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0x7e, 0x80, 
    0xbd, 0x80, 
    0xc3, 0x80, 
    0xff, 0x80, 
    0xff, 0x80, 
    0xff, 0x80
};
static const tImage Font_0x55 = { image_data_Font_0x55,
    9, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x56[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙██
    // █∙███∙██
    // █∙███∙██
    // ██∙█∙███
    // ██∙█∙███
    // ██∙█∙███
    // ███∙████
    // ███∙████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0x7d, 
    0xbb, 
    0xbb, 
    0xbb, 
    0xd7, 
    0xd7, 
    0xd7, 
    0xef, 
    0xef, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x56 = { image_data_Font_0x56,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x57[34] = {
    // ██████████████
    // ██████████████
    // ██████████████
    // ██████████████
    // ∙█████∙█████∙█
    // ∙████∙█∙████∙█
    // █∙███∙█∙███∙██
    // █∙███∙█∙███∙██
    // █∙███∙█∙███∙██
    // █∙██∙███∙██∙██
    // ██∙█∙███∙█∙███
    // ██∙█∙███∙█∙███
    // ██∙∙█████∙∙███
    // ███∙█████∙████
    // ██████████████
    // ██████████████
    // ██████████████
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0x7d, 0xf4, 
    0x7a, 0xf4, 
    0xba, 0xec, 
    0xba, 0xec, 
    0xba, 0xec, 
    0xb7, 0x6c, 
    0xd7, 0x5c, 
    0xd7, 0x5c, 
    0xcf, 0x9c, 
    0xef, 0xbc, 
    0xff, 0xfc, 
    0xff, 0xfc, 
    0xff, 0xfc
};
static const tImage Font_0x57 = { image_data_Font_0x57,
    14, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x58[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // █∙███∙██
    // █∙███∙██
    // ██∙█∙███
    // ███∙████
    // ███∙████
    // ██∙█∙███
    // █∙███∙██
    // █∙███∙██
    // ∙█████∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0xbb, 
    0xbb, 
    0xd7, 
    0xef, 
    0xef, 
    0xd7, 
    0xbb, 
    0xbb, 
    0x7d, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x58 = { image_data_Font_0x58,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x59[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // █∙███∙██
    // █∙███∙██
    // ██∙█∙███
    // ██∙█∙███
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ███∙████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0xbb, 
    0xbb, 
    0xd7, 
    0xd7, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xef, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x59 = { image_data_Font_0x59,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5a[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙█
    // ██████∙█
    // █████∙██
    // ████∙███
    // ███∙████
    // ███∙████
    // ██∙█████
    // █∙██████
    // ∙███████
    // ∙∙∙∙∙∙∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x01, 
    0xfd, 
    0xfb, 
    0xf7, 
    0xef, 
    0xef, 
    0xdf, 
    0xbf, 
    0x7f, 
    0x01, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x5a = { image_data_Font_0x5a,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5b[17] = {
    // █████
    // █████
    // █████
    // ∙∙∙∙█
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙∙∙∙█
    0xf8, 
    0xf8, 
    0xf8, 
    0x08, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x08
};
static const tImage Font_0x5b = { image_data_Font_0x5b,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5c[17] = {
    // █████
    // █████
    // █████
    // ∙████
    // ∙████
    // █∙███
    // █∙███
    // █∙███
    // ██∙██
    // ██∙██
    // ██∙██
    // ███∙█
    // ███∙█
    // ███∙█
    // ████∙
    // ████∙
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0x78, 
    0x78, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xf0, 
    0xf0, 
    0xf8
};
static const tImage Font_0x5c = { image_data_Font_0x5c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5d[17] = {
    // █████
    // █████
    // █████
    // ∙∙∙∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ███∙█
    // ∙∙∙∙█
    0xf8, 
    0xf8, 
    0xf8, 
    0x08, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0xe8, 
    0x08
};
static const tImage Font_0x5d = { image_data_Font_0x5d,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5e[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ████∙∙████
    // ███∙██∙███
    // ███∙██∙███
    // ██∙████∙██
    // █∙██████∙█
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xf3, 0xc0, 
    0xed, 0xc0, 
    0xed, 0xc0, 
    0xde, 0xc0, 
    0xbf, 0x40, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x5e = { image_data_Font_0x5e,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x5f[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙∙∙∙∙∙∙∙
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x00, 
    0xff
};
static const tImage Font_0x5f = { image_data_Font_0x5f,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x60[17] = {
    // ████████
    // ████████
    // ███∙████
    // ███∙████
    // ████∙███
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xef, 
    0xef, 
    0xf7, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x60 = { image_data_Font_0x60,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x61[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ██∙∙∙██
    // █∙███∙█
    // █████∙█
    // ██∙∙∙∙█
    // █∙███∙█
    // ∙████∙█
    // ∙███∙∙█
    // █∙∙∙█∙█
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xc6, 
    0xba, 
    0xfa, 
    0xc2, 
    0xba, 
    0x7a, 
    0x72, 
    0x8a, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x61 = { image_data_Font_0x61,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x62[17] = {
    // ████████
    // ████████
    // ████████
    // ∙███████
    // ∙███████
    // ∙███████
    // ∙█∙∙∙███
    // ∙∙███∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙████∙██
    // ∙∙∙∙∙███
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0x7f, 
    0x7f, 
    0x7f, 
    0x47, 
    0x3b, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7b, 
    0x07, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x62 = { image_data_Font_0x62,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x63[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ██∙∙∙██
    // █∙███∙█
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙██████
    // █∙███∙█
    // ██∙∙∙██
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xc6, 
    0xba, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x7e, 
    0xba, 
    0xc6, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x63 = { image_data_Font_0x63,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x64[17] = {
    // ████████
    // ████████
    // ████████
    // ██████∙█
    // ██████∙█
    // ██████∙█
    // ██∙∙∙∙∙█
    // █∙████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙∙█
    // ██∙∙∙█∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xfd, 
    0xfd, 
    0xfd, 
    0xc1, 
    0xbd, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xb9, 
    0xc5, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x64 = { image_data_Font_0x64,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x65[17] = {
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ███████
    // ██∙∙∙██
    // █∙███∙█
    // ∙████∙█
    // ∙∙∙∙∙∙█
    // ∙██████
    // ∙██████
    // █∙███∙█
    // ██∙∙∙██
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xfe, 
    0xc6, 
    0xba, 
    0x7a, 
    0x02, 
    0x7e, 
    0x7e, 
    0xba, 
    0xc6, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x65 = { image_data_Font_0x65,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x66[17] = {
    // █████
    // █████
    // █████
    // ██∙∙∙
    // █∙███
    // █∙███
    // ∙∙∙∙█
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xc0, 
    0xb8, 
    0xb8, 
    0x08, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x66 = { image_data_Font_0x66,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x67[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙∙█
    // █∙████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙∙█
    // ██∙∙∙█∙█
    // ██████∙█
    // █∙███∙██
    // ██∙∙∙███
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc1, 
    0xbd, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xb9, 
    0xc5, 
    0xfd, 
    0xbb, 
    0xc7
};
static const tImage Font_0x67 = { image_data_Font_0x67,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x68[17] = {
    // ████████
    // ████████
    // ████████
    // ∙███████
    // ∙███████
    // ∙███████
    // ∙█∙∙∙∙██
    // ∙∙████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0x7f, 
    0x7f, 
    0x7f, 
    0x43, 
    0x3d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x68 = { image_data_Font_0x68,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x69[17] = {
    // ██
    // ██
    // ██
    // ██
    // ∙█
    // ██
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ██
    // ██
    // ██
    0xc0, 
    0xc0, 
    0xc0, 
    0xc0, 
    0x40, 
    0xc0, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0xc0, 
    0xc0, 
    0xc0
};
static const tImage Font_0x69 = { image_data_Font_0x69,
    2, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6a[17] = {
    // ████
    // ████
    // ████
    // ████
    // ██∙█
    // ████
    // ∙∙∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ██∙█
    // ∙∙██
    0xf0, 
    0xf0, 
    0xf0, 
    0xf0, 
    0xd0, 
    0xf0, 
    0x10, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0xd0, 
    0x30
};
static const tImage Font_0x6a = { image_data_Font_0x6a,
    4, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6b[17] = {
    // ███████
    // ███████
    // ███████
    // ∙██████
    // ∙██████
    // ∙██████
    // ∙███∙██
    // ∙██∙███
    // ∙█∙████
    // ∙∙█████
    // ∙█∙████
    // ∙██∙███
    // ∙███∙██
    // ∙████∙█
    // ███████
    // ███████
    // ███████
    0xfe, 
    0xfe, 
    0xfe, 
    0x7e, 
    0x7e, 
    0x7e, 
    0x76, 
    0x6e, 
    0x5e, 
    0x3e, 
    0x5e, 
    0x6e, 
    0x76, 
    0x7a, 
    0xfe, 
    0xfe, 
    0xfe
};
static const tImage Font_0x6b = { image_data_Font_0x6b,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6c[17] = {
    // ██
    // ██
    // ██
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ∙█
    // ██
    // ██
    // ██
    0xc0, 
    0xc0, 
    0xc0, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0xc0, 
    0xc0, 
    0xc0
};
static const tImage Font_0x6c = { image_data_Font_0x6c,
    2, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6d[34] = {
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // ████████████
    // █∙█∙∙██∙∙███
    // █∙∙██∙∙██∙██
    // █∙███∙███∙██
    // █∙███∙███∙██
    // █∙███∙███∙██
    // █∙███∙███∙██
    // █∙███∙███∙██
    // █∙███∙███∙██
    // ████████████
    // ████████████
    // ████████████
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xa6, 0x70, 
    0x99, 0xb0, 
    0xbb, 0xb0, 
    0xbb, 0xb0, 
    0xbb, 0xb0, 
    0xbb, 0xb0, 
    0xbb, 0xb0, 
    0xbb, 0xb0, 
    0xff, 0xf0, 
    0xff, 0xf0, 
    0xff, 0xf0
};
static const tImage Font_0x6d = { image_data_Font_0x6d,
    12, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6e[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█∙∙∙∙██
    // ∙∙████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x43, 
    0x3d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x6e = { image_data_Font_0x6e,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x6f[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙███
    // █∙███∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙██
    // ██∙∙∙███
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc7, 
    0xbb, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xbb, 
    0xc7, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x6f = { image_data_Font_0x6f,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x70[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█∙∙∙███
    // ∙∙███∙██
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙████∙██
    // ∙∙∙∙∙███
    // ∙███████
    // ∙███████
    // ∙███████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x47, 
    0x3b, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7b, 
    0x07, 
    0x7f, 
    0x7f, 
    0x7f
};
static const tImage Font_0x70 = { image_data_Font_0x70,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x71[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ██∙∙∙∙∙█
    // █∙████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙∙█
    // ██∙∙∙█∙█
    // ██████∙█
    // ██████∙█
    // ██████∙█
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xc1, 
    0xbd, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0xb9, 
    0xc5, 
    0xfd, 
    0xfd, 
    0xfd
};
static const tImage Font_0x71 = { image_data_Font_0x71,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x72[17] = {
    // █████
    // █████
    // █████
    // █████
    // █████
    // █████
    // ∙█∙∙█
    // ∙∙███
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // ∙████
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0x48, 
    0x38, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0x78, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x72 = { image_data_Font_0x72,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x73[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // █∙∙∙██
    // ∙███∙█
    // ∙█████
    // █∙∙███
    // ███∙██
    // ████∙█
    // ∙███∙█
    // █∙∙∙██
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0x8c, 
    0x74, 
    0x7c, 
    0x9c, 
    0xec, 
    0xf4, 
    0x74, 
    0x8c, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x73 = { image_data_Font_0x73,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x74[17] = {
    // █████
    // █████
    // █████
    // █████
    // █∙███
    // █∙███
    // ∙∙∙∙∙
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // █∙███
    // ██∙∙∙
    // █████
    // █████
    // █████
    0xf8, 
    0xf8, 
    0xf8, 
    0xf8, 
    0xb8, 
    0xb8, 
    0x00, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xb8, 
    0xc0, 
    0xf8, 
    0xf8, 
    0xf8
};
static const tImage Font_0x74 = { image_data_Font_0x74,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x75[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙█████∙█
    // ∙████∙∙█
    // █∙∙∙∙█∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x7d, 
    0x79, 
    0x85, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x75 = { image_data_Font_0x75,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x76[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙██
    // █∙███∙██
    // ██∙█∙███
    // ██∙█∙███
    // ███∙████
    // ███∙████
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0x7d, 
    0xbb, 
    0xbb, 
    0xd7, 
    0xd7, 
    0xef, 
    0xef, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x76 = { image_data_Font_0x76,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x77[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ∙███∙███∙█
    // ∙███∙███∙█
    // █∙█∙█∙█∙██
    // █∙█∙█∙█∙██
    // █∙█∙█∙█∙██
    // █∙█∙█∙█∙██
    // ██∙███∙███
    // ██∙███∙███
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0x77, 0x40, 
    0x77, 0x40, 
    0xaa, 0xc0, 
    0xaa, 0xc0, 
    0xaa, 0xc0, 
    0xaa, 0xc0, 
    0xdd, 0xc0, 
    0xdd, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x77 = { image_data_Font_0x77,
    10, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x78[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // █∙███∙██
    // ██∙█∙███
    // ███∙████
    // ███∙████
    // ██∙█∙███
    // █∙███∙██
    // ∙█████∙█
    // ████████
    // ████████
    // ████████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0xbb, 
    0xd7, 
    0xef, 
    0xef, 
    0xd7, 
    0xbb, 
    0x7d, 
    0xff, 
    0xff, 
    0xff
};
static const tImage Font_0x78 = { image_data_Font_0x78,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x79[17] = {
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ████████
    // ∙█████∙█
    // ∙█████∙█
    // █∙███∙██
    // █∙███∙██
    // ██∙█∙███
    // ██∙█∙███
    // ███∙████
    // ███∙████
    // ███∙████
    // ██∙█████
    // ██∙█████
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0xff, 
    0x7d, 
    0x7d, 
    0xbb, 
    0xbb, 
    0xd7, 
    0xd7, 
    0xef, 
    0xef, 
    0xef, 
    0xdf, 
    0xdf
};
static const tImage Font_0x79 = { image_data_Font_0x79,
    8, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7a[17] = {
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ██████
    // ∙∙∙∙∙█
    // ████∙█
    // ███∙██
    // ██∙███
    // ██∙███
    // █∙████
    // ∙█████
    // ∙∙∙∙∙█
    // ██████
    // ██████
    // ██████
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0xfc, 
    0x04, 
    0xf4, 
    0xec, 
    0xdc, 
    0xdc, 
    0xbc, 
    0x7c, 
    0x04, 
    0xfc, 
    0xfc, 
    0xfc
};
static const tImage Font_0x7a = { image_data_Font_0x7a,
    6, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7b[17] = {
    // ███████
    // ███████
    // ███████
    // ███∙∙██
    // ██∙████
    // ██∙████
    // ██∙████
    // ██∙████
    // ██∙████
    // ∙∙█████
    // ██∙████
    // ██∙████
    // ██∙████
    // ██∙████
    // ██∙████
    // ██∙████
    // ███∙∙██
    0xfe, 
    0xfe, 
    0xfe, 
    0xe6, 
    0xde, 
    0xde, 
    0xde, 
    0xde, 
    0xde, 
    0x3e, 
    0xde, 
    0xde, 
    0xde, 
    0xde, 
    0xde, 
    0xde, 
    0xe6
};
static const tImage Font_0x7b = { image_data_Font_0x7b,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7c[17] = {
    // █████
    // █████
    // █████
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    // ██∙██
    0xf8, 
    0xf8, 
    0xf8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8, 
    0xd8
};
static const tImage Font_0x7c = { image_data_Font_0x7c,
    5, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7d[17] = {
    // ███████
    // ███████
    // ███████
    // █∙∙████
    // ███∙███
    // ███∙███
    // ███∙███
    // ███∙███
    // ███∙███
    // ████∙∙█
    // ███∙███
    // ███∙███
    // ███∙███
    // ███∙███
    // ███∙███
    // ███∙███
    // █∙∙████
    0xfe, 
    0xfe, 
    0xfe, 
    0x9e, 
    0xee, 
    0xee, 
    0xee, 
    0xee, 
    0xee, 
    0xf2, 
    0xee, 
    0xee, 
    0xee, 
    0xee, 
    0xee, 
    0xee, 
    0x9e
};
static const tImage Font_0x7d = { image_data_Font_0x7d,
    7, 17, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_Font_0x7e[34] = {
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██∙∙████∙█
    // █∙██∙███∙█
    // █∙███∙██∙█
    // █∙████∙∙██
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    // ██████████
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xcf, 0x40, 
    0xb7, 0x40, 
    0xbb, 0x40, 
    0xbc, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0, 
    0xff, 0xc0
};
static const tImage Font_0x7e = { image_data_Font_0x7e,
    10, 17, 8};
#endif


static const tChar Font_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &Font_0x20},
#else
  // character: ' ' == ''
  {0x20, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &Font_0x21},
#else
  // character: '!' == ''
  {0x21, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &Font_0x22},
#else
  // character: '"' == ''
  {0x22, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &Font_0x23},
#else
  // character: '#' == ''
  {0x23, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &Font_0x24},
#else
  // character: '$' == ''
  {0x24, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &Font_0x25},
#else
  // character: '%' == ''
  {0x25, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &Font_0x26},
#else
  // character: '&' == ''
  {0x26, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &Font_0x27},
#else
  // character: ''' == ''
  {0x27, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &Font_0x28},
#else
  // character: '(' == ''
  {0x28, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &Font_0x29},
#else
  // character: ')' == ''
  {0x29, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &Font_0x2a},
#else
  // character: '*' == ''
  {0x2a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &Font_0x2b},
#else
  // character: '+' == ''
  {0x2b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &Font_0x2c},
#else
  // character: ',' == ''
  {0x2c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &Font_0x2d},
#else
  // character: '-' == ''
  {0x2d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &Font_0x2e},
#else
  // character: '.' == ''
  {0x2e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &Font_0x2f},
#else
  // character: '/' == ''
  {0x2f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &Font_0x30},
#else
  // character: '0' == ''
  {0x30, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &Font_0x31},
#else
  // character: '1' == ''
  {0x31, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &Font_0x32},
#else
  // character: '2' == ''
  {0x32, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &Font_0x33},
#else
  // character: '3' == ''
  {0x33, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &Font_0x34},
#else
  // character: '4' == ''
  {0x34, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &Font_0x35},
#else
  // character: '5' == ''
  {0x35, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &Font_0x36},
#else
  // character: '6' == ''
  {0x36, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &Font_0x37},
#else
  // character: '7' == ''
  {0x37, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &Font_0x38},
#else
  // character: '8' == ''
  {0x38, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &Font_0x39},
#else
  // character: '9' == ''
  {0x39, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &Font_0x3a},
#else
  // character: ':' == ''
  {0x3a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &Font_0x3b},
#else
  // character: ';' == ''
  {0x3b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &Font_0x3c},
#else
  // character: '<' == ''
  {0x3c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &Font_0x3d},
#else
  // character: '=' == ''
  {0x3d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &Font_0x3e},
#else
  // character: '>' == ''
  {0x3e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &Font_0x3f},
#else
  // character: '?' == ''
  {0x3f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &Font_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &Font_0x41},
#else
  // character: 'A' == ''
  {0x41, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &Font_0x42},
#else
  // character: 'B' == ''
  {0x42, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &Font_0x43},
#else
  // character: 'C' == ''
  {0x43, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &Font_0x44},
#else
  // character: 'D' == ''
  {0x44, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &Font_0x45},
#else
  // character: 'E' == ''
  {0x45, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &Font_0x46},
#else
  // character: 'F' == ''
  {0x46, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &Font_0x47},
#else
  // character: 'G' == ''
  {0x47, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &Font_0x48},
#else
  // character: 'H' == ''
  {0x48, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &Font_0x49},
#else
  // character: 'I' == ''
  {0x49, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &Font_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &Font_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &Font_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &Font_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &Font_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &Font_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &Font_0x50},
#else
  // character: 'P' == ''
  {0x50, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &Font_0x51},
#else
  // character: 'Q' == ''
  {0x51, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &Font_0x52},
#else
  // character: 'R' == ''
  {0x52, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &Font_0x53},
#else
  // character: 'S' == ''
  {0x53, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &Font_0x54},
#else
  // character: 'T' == ''
  {0x54, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &Font_0x55},
#else
  // character: 'U' == ''
  {0x55, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &Font_0x56},
#else
  // character: 'V' == ''
  {0x56, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &Font_0x57},
#else
  // character: 'W' == ''
  {0x57, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &Font_0x58},
#else
  // character: 'X' == ''
  {0x58, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &Font_0x59},
#else
  // character: 'Y' == ''
  {0x59, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &Font_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &Font_0x5b},
#else
  // character: '[' == ''
  {0x5b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &Font_0x5c},
#else
  // character: '\' == ''
  {0x5c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &Font_0x5d},
#else
  // character: ']' == ''
  {0x5d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &Font_0x5e},
#else
  // character: '^' == ''
  {0x5e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &Font_0x5f},
#else
  // character: '_' == ''
  {0x5f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &Font_0x60},
#else
  // character: '`' == ''
  {0x60, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &Font_0x61},
#else
  // character: 'a' == ''
  {0x61, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &Font_0x62},
#else
  // character: 'b' == ''
  {0x62, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &Font_0x63},
#else
  // character: 'c' == ''
  {0x63, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &Font_0x64},
#else
  // character: 'd' == ''
  {0x64, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &Font_0x65},
#else
  // character: 'e' == ''
  {0x65, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &Font_0x66},
#else
  // character: 'f' == ''
  {0x66, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &Font_0x67},
#else
  // character: 'g' == ''
  {0x67, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &Font_0x68},
#else
  // character: 'h' == ''
  {0x68, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &Font_0x69},
#else
  // character: 'i' == ''
  {0x69, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &Font_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &Font_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'l'
  {0x6c, &Font_0x6c},
#else
  // character: 'l' == ''
  {0x6c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &Font_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &Font_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &Font_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &Font_0x70},
#else
  // character: 'p' == ''
  {0x70, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &Font_0x71},
#else
  // character: 'q' == ''
  {0x71, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &Font_0x72},
#else
  // character: 'r' == ''
  {0x72, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &Font_0x73},
#else
  // character: 's' == ''
  {0x73, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &Font_0x74},
#else
  // character: 't' == ''
  {0x74, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &Font_0x75},
#else
  // character: 'u' == ''
  {0x75, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &Font_0x76},
#else
  // character: 'v' == ''
  {0x76, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &Font_0x77},
#else
  // character: 'w' == ''
  {0x77, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &Font_0x78},
#else
  // character: 'x' == ''
  {0x78, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &Font_0x79},
#else
  // character: 'y' == ''
  {0x79, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &Font_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &Font_0x7b},
#else
  // character: '{' == ''
  {0x7b, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &Font_0x7c},
#else
  // character: '|' == ''
  {0x7c, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &Font_0x7d},
#else
  // character: '}' == ''
  {0x7d, &Font_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &Font_0x7e}
#else
  // character: '~' == ''
  {0x7e, &Font_0x}
#endif

};


const tFont Font = { 95, Font_array };

